return {
	"wsgggws/sparks.nvim",
	-- dir = "~/github/sparks.nvim",
	event = "VeryLazy",
	opts = {
		-- 🚀 默认已启用所有最佳配置
		triggers = {
			-- 自定义特效绑定示例
			["@"] = "nghuhu",
			["/"] = "yueyue",
			["&"] = "manman",
			["+"] = "shenyiao",
			["\\"] = "yueyue",
			["?"] = "manman",
			["!"] = "nghuhu",
			["`"] = "shenyiao",
			["-"] = "shenyiao",
			["*"] = "nghuhu",
			["("] = "yueyue",
			["["] = "manman",
			["{"] = "yueyue",
			["<"] = "manman",
			[">"] = "nghuhu",
			["="] = "shenyiao",
			[";"] = "manman",
			[","] = "yueyue",
			["."] = "nghuhu",
			["'"] = "shenyiao",
			['"'] = "nghuhu",
			[":"] = "manman",
			["~"] = "yueyue",
			["^"] = "shenyiao",
		},
	},
}
